name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker-compose -f compose.test.yaml up -d
      - run: |
          timeout 60 bash -c 'until nc -z localhost 2222; do sleep 2; done'
          sleep 5
      - uses: ./
        env:
          HOST: localhost
          USERNAME: root
          PASSWORD: testpassword
          PORT: 2222
      - if: always()
        run: docker-compose -f compose.test.yaml down
